### ISSUE TITLE
`cozo-node` install fails with `TAR_BAD_ARCHIVE: Unrecognized archive format`

### ISSUE THREAD

**Issue by loveencounterflow** [cozodb/cozo#28]
When trying to do `pnpm add cozo-node` or `npm install cozo-node`, I'm getting a `TAR_BAD_ARCHIVE: Unrecognized archive format` error both under NodeJS v14 and v19. Full stacktrace:

```
.../node_modules/cozo-node install$ node-pre-gyp install
│ node-pre-gyp info it worked if it ends with ok
│ node-pre-gyp info using node-pre-gyp@1.0.10
│ node-pre-gyp info using node@14.21.2 | linux | x64
│ node-pre-gyp info check checked for "/tmp/cozo-demo/node_modules/.pnpm/cozo-node@0.3.0/node_modules/cozo-node/native/6/index.node" (not found)
│ node-pre-gyp http GET https://github.com/cozodb/cozo-lib-nodejs/releases/download/0.3.0/6-linux-x64.tar.gz
│ node-pre-gyp ERR! install TAR_BAD_ARCHIVE: Unrecognized archive format 
│ node-pre-gyp ERR! install error 
│ node-pre-gyp ERR! stack Error: TAR_BAD_ARCHIVE: Unrecognized archive format
│ node-pre-gyp ERR! stack     at Unpack.warn (/tmp/cozo-demo/node_modules/.pnpm/tar@6.1.13/node_modules/tar/lib/warn-mixin.js:21:40)
│ node-pre-gyp ERR! stack     at Unpack.warn (/tmp/cozo-demo/node_modules/.pnpm/tar@6.1.13/node_modules/tar/lib/unpack.js:229:18)
│ node-pre-gyp ERR! stack     at Unpack.<anonymous> (/tmp/cozo-demo/node_modules/.pnpm/tar@6.1.13/node_modules/tar/lib/parse.js:83:14)
│ node-pre-gyp ERR! stack     at Unpack.emit (events.js:412:35)
│ node-pre-gyp ERR! stack     at Unpack.[emit] (/tmp/cozo-demo/node_modules/.pnpm/tar@6.1.13/node_modules/tar/lib/parse.js:303:12)
│ node-pre-gyp ERR! stack     at Unpack.[maybeEnd] (/tmp/cozo-demo/node_modules/.pnpm/tar@6.1.13/node_modules/tar/lib/parse.js:426:17)
│ node-pre-gyp ERR! stack     at Unpack.[consumeChunk] (/tmp/cozo-demo/node_modules/.pnpm/tar@6.1.13/node_modules/tar/lib/parse.js:458:21)
│ node-pre-gyp ERR! stack     at Unzip.<anonymous> (/tmp/cozo-demo/node_modules/.pnpm/tar@6.1.13/node_modules/tar/lib/parse.js:372:29)
│ node-pre-gyp ERR! stack     at Unzip.emit (events.js:412:35)
│ node-pre-gyp ERR! stack     at Unzip.[emitEnd2] (/tmp/cozo-demo/node_modules/.pnpm/minipass@3.3.6/node_modules/minipass/index.js:524:23)
│ node-pre-gyp ERR! System Linux 5.15.0-53-generic
│ node-pre-gyp ERR! command "/usr/local/bin/node" "/tmp/cozo-demo/node_modules/.pnpm/@mapbox+node-pre-gyp@1.0.10/node_modules/@mapbox/node-pre-gyp/bin/node-pre-gyp" "install"
│ node-pre-gyp ERR! cwd /tmp/cozo-demo/node_modules/.pnpm/cozo-node@0.3.0/node_modules/cozo-node
│ node-pre-gyp ERR! node -v v14.21.2
│ node-pre-gyp ERR! node-pre-gyp -v v1.0.10
│ node-pre-gyp ERR! not ok 
│ TAR_BAD_ARCHIVE: Unrecognized archive format
```

**Comment by zh217** [comment]
Thanks for the catch! It's caused by a bad build script which gzipped the file without tar, which node-pre-gyp expects.

It's been fixed, please try installing again.

**Comment by loveencounterflow** [comment]
That did install in a breeze, thx a bunch for the very fast fix! Happy holidays!
