### ISSUE TITLE
Thread exhausted by large number of queires

### ISSUE THREAD

**Issue by chuanqisun** [cozodb/cozo#78]
When performing a large number of operations, I consistently receive thread exhaustion error. It feels like the thread was not being freed (either not being freed in time, or not being freed at all) after each query.

Repro (node.js)
```bash
RUST_BACKTRACE=full node ./repro.js
```

```javascript
const { CozoDb } = require("cozo-node");

async function main() {
  const db = new CozoDb();

  let iter = 0;

  while (iter++ < 1000000) {
    await db.run(` ?[] <- [[""]]`);

    if (iter % 100 === 0) {
      console.log(iter);
    }
  }
}

main();
```

Output
```
100
200
...
30800
30900
31000
31100
31200
31300
thread '<unnamed>' panicked at 'failed to spawn thread: Os { code: 11, kind: WouldBlock, message: "Resource temporarily unavailable" }', /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/thread/mod.rs:715:29
stack backtrace:
   0:     0x7f02855123f0 - std::backtrace_rs::backtrace::libunwind::trace::h595f06c70adcc478
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x7f02855123f0 - std::backtrace_rs::backtrace::trace_unsynchronized::h177a0149c76cdde9
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x7f02855123f0 - std::sys_common::backtrace::_print_fmt::hc0701fd2c3530c58
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x7f02855123f0 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd4cd115d8750fd6c
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x7f02850298be - core::fmt::write::h93e2f5923c7eca08
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/fmt/mod.rs:1213:17
   5:     0x7f02854edae4 - std::io::Write::write_fmt::h8162dbb45f0b9e62
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/io/mod.rs:1682:15
   6:     0x7f0285513bff - std::sys_common::backtrace::_print::h1835ef8a8f9066da
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x7f0285513bff - std::sys_common::backtrace::print::hcb5e6388b9235f41
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x7f02855137ff - std::panicking::default_hook::{{closure}}::h9c084969ccf9a722
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:267:22
   9:     0x7f02855148b6 - std::panicking::default_hook::h68fa2ba3c3c6c12f
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:286:9
  10:     0x7f02855148b6 - std::panicking::rust_panic_with_hook::h8d5c434518ef298c
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:688:13
  11:     0x7f0285514364 - std::panicking::begin_panic_handler::{{closure}}::hf33414f5dabf6faf
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:579:13
  12:     0x7f02855142cc - std::sys_common::backtrace::__rust_end_short_backtrace::hc50389427413bb75
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys_common/backtrace.rs:137:18
  13:     0x7f02855142a1 - rust_begin_unwind
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:575:5
  14:     0x7f0284f8f632 - core::panicking::panic_fmt::h2de7a7938f816de8
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/panicking.rs:64:14
  15:     0x7f0284f8fa92 - core::result::unwrap_failed::hdc73d4affce1d414
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/result.rs:1790:5
  16:     0x7f02851351be - cozo::runtime::db::Poison::set_timeout::h0e7ced27714c26cc
  17:     0x7f0285139559 - cozo::runtime::db::Db<S>::run_query::hb8ae4d482dec4fc0
  18:     0x7f0285138eb4 - cozo::runtime::db::Db<S>::execute_single_program::h2f2e1b626910ed53
  19:     0x7f028513c40a - cozo::runtime::db::Db<S>::run_script::ha39e45fccbe8422f
  20:     0x7f02853a53cb - std::sys_common::backtrace::__rust_begin_short_backtrace::h1aa3d078f52cd66e
  21:     0x7f02853a2d53 - core::ops::function::FnOnce::call_once{{vtable.shim}}::h9df442b5b8069cae
  22:     0x7f0285515425 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h1c0f3664d7ced314
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/alloc/src/boxed.rs:1988:9
  23:     0x7f0285515425 - <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once::h67647c21c6c4968a
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/alloc/src/boxed.rs:1988:9
  24:     0x7f0285515425 - std::sys::unix::thread::Thread::new::thread_start::h355d348ba593a22c
                               at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/sys/unix/thread.rs:108:17
  25:     0x7f028cf14609 - start_thread
  26:     0x7f028ce39133 - clone
  27:                0x0 - <unknown>

```

Additional env details: 
```
npm ls cozo-node
  cozo-node@0.6.0

node -v
  v18.4.0

uname -a:
  Linux <*****> 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

installed binary:
  native/6/cozo_node_prebuilt.node
```

**Comment by chuanqisun** [comment]
I was able to confirm that the thread count increases monotonically after each `db.run`, using the techniques documented here: https://stackoverflow.com/questions/268680/how-can-i-monitor-the-thread-count-of-a-process-on-linux

**Comment by zh217** [comment]
thanks for the report. seems the nodejs interop code needs some further
work. will fix when I find the root problem.

Chuánqí Sun ***@***.***> 于 2023年4月29日周六 05:25写道：

**Comment by zh217** [comment]
I've found the problem, it has nothing to do with the NodeJS specific code. Rather it is because the new default timeout of 60 seconds causing problems.

This will be fixed soon. In the meantime, you can explicitly set `:timeout 0` in your queries to disable the feature and the problem will go away.

**Comment by chuanqisun** [comment]
Thanks! Let me know if you need additional diagnostics. I'm a node developer with a entry-level rust knowledge. I did a quick GPT-4 query. Sharing the suggestion just for reference.

> System message: You are a senior Rust developer. You are analyzing the following code
> (source code of `cozo-lib-nodejs/src/lib.rs`)
>
> User message: There is an issue with the thread management. After each query_db call, the thread is not freed up. Where is the problem?
>
> Assistant message:
> The problem lies in the way the threads are spawned and the channels are used in functions like query_db, query_tx, backup_db, restore_db, export_relations, import_relations, import_from_backup, and register_named_rule. These threads are spawned but not joined or terminated explicitly after their tasks are complete. The channel's sender and receiver are dropped automatically after their usage, which should terminate the thread, but it's not guaranteed. 
> 
> To fix this issue, you can use a thread pool with a limited number of threads and an explicit way to signal task completion. For example, you can use the rayon crate to create a thread pool, and then replace the thread::spawn calls with the rayon::spawn calls. This way, the threads will be managed by the thread pool, and they will be reused and terminated appropriately. 
> 

GPT suggested edits
```rs
use rayon::ThreadPoolBuilder;  
let pool = ThreadPoolBuilder::new()  
    .num_threads(4)  
    .build()  
    .expect("Failed to build thread pool");  
pool.spawn(move || {  
    let result = db.run_script(&query, params);  
    channel.send(move |mut cx| {  
        // ... (the rest of the code remains the same)  
    });  
});  
```

**Comment by chuanqisun** [comment]
Oh, just saw your updated response. Disregard my message above.

**Comment by chuanqisun** [comment]
Confirmed `:timeout 0` works like a charm in all of my real use cases. Thanks again!

**Comment by zh217** [comment]
Fixed
