### ISSUE TITLE
System panic on modulo by zero

### ISSUE THREAD

**Issue by DerZc** [cozodb/cozo#99]
Hi,

I found modulo by zero will cause system panic. Consider the following program:

```
aoza[a] <- [[true]]

rpnt[K] := K = mod(5, 0)
?[a] := rpnt[a]
```
This program will return `RuntimeError: unreachable` in https://www.cozodb.org/wasm-demo/, but will return `pyo3_runtime.PanicException: attempt to calculate the remainder with a divisor of zero` in Python. 

This is a python program to reproduce this:
```
from pycozo.client import Client

client = Client()
script = '''
aoza[a] <- [[true]]

rpnt[K] := K = 5 % 0
?[a] := rpnt[a]
'''
r = client.run(script)

print(r)
```

This is the whole error message:
```
root@553cb7e5fab7:/home# python3 test.py thread '<unnamed>' panicked at 'attempt to calculate the remainder with a divisor of zero', /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/ops/arith.rs:584:45
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Traceback (most recent call last):
  File "test.py", line 10, in <module>
    r = client.run(script)
  File "/usr/local/lib/python3.8/dist-packages/pycozo/client.py", line 112, in run
    return self._embedded_request(script, params)
  File "/usr/local/lib/python3.8/dist-packages/pycozo/client.py", line 94, in _embedded_request
    res = self.embedded.run_script(script, params or {})
pyo3_runtime.PanicException: attempt to calculate the remainder with a divisor of zero
```
Although modulo by zero is not allowed, but maybe an error message or assertion failure is better.

**Comment by zh217** [comment]
Thanks, you are really good at finding bugs!

**Comment by DerZc** [comment]
So happy that this report was useful to you, thank you for your efficient work!
